# Generated by Django 3.1 on 2020-09-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, unique=True)),
                ('uName', models.CharField(max_length=30)),
                ('uPassword', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='taluka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='village',
            fields=[
                ('villageName', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('taluka', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='apis.taluka')),
            ],
            options={
                'verbose_name': 'Village List',
                'db_table': 'village',
            },
        ),
        migrations.CreateModel(
            name='visitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_name', models.CharField(max_length=70)),
                ('visit_date', models.CharField(max_length=70)),
                ('visit_reason', models.CharField(max_length=200)),
                ('visit_to_be', models.CharField(max_length=200)),
                ('visit_contact', models.CharField(max_length=100)),
                ('visit_help', models.CharField(max_length=200)),
                ('visit_remark', models.CharField(max_length=200)),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.login')),
                ('villageName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.village')),
            ],
        ),
    ]
