# Generated by Django 3.1 on 2020-09-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200929_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='entry_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.login'),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='villageName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apis.village'),
        ),
    ]
