# Generated by Django 3.1 on 2020-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200929_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='uName',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='uPassword',
            field=models.CharField(max_length=15),
        ),
    ]
